tasks:
  - init: |
      python -m venv venv
      source venv/bin/activate
      pip install --upgrade pip wheel setuptools
      pip install Django
      pip install django-tailwind
      python manage.py migrate
    command: |
      source venv/bin/activate
  - name: tailwind
    command: python manage.py tailwind start
  - name: server
    command: python manage.py runserver
  
ports:
  - port: 8000
    visibility: private
    onOpen: open-preview

vscode:
  extensions:
    - ms-python.python
    - batisteo.vscode-django
