tasks:
  - init: |
      python -m venv venv
      source venv/bin/activate
      pip install --upgrade pip wheel setuptools
      pip install Django
      pip install django-tailwind
      python manage.py migrate
      gp sync-done setup
    command: |
      source venv/bin/activate
  - name: tailwind
    init: |
      gp sync-await setup
      python manage.py tailwind install
      gp sync-done build
    command: python manage.py tailwind start
  - name: server
    init: gp sync-await build
    command: python manage.py runserver
    openMode: split-right
  
ports:
  - port: 8000
    visibility: private
    onOpen: open-preview

vscode:
  extensions:
    - ms-python.python
    - batisteo.vscode-django
